// list
export const REQUEST_LIST = 'REQUEST_LIST';
export const RECEIVE_LIST = 'RECEIVE_LIST';
export const RECEIVE_LIST_ERROR = 'RECEIVE_LIST_ERROR';

// add items
export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM';
export const RECEIVE_ADD_ITEM = 'RECEIVE_ADD_ITEM';
export const RECEIVE_ADD_ITEM_ERROR = 'RECEIVE_ADD_ITEM_ERROR';

// pagination
export const REQUEST_INITIAL_PAGE = 'REQUEST_INITIAL_PAGE';
export const RECEIVE_INITIAL_PAGE = 'RECEIVE_INITIAL_PAGE';
export const RECEIVE_INITIAL_PAGE_ERROR = 'RECEIVE_INITIAL_PAGE_ERROR';

export const REQUEST_NEXT_PAGE = 'REQUEST_NEXT_PAGE';
export const RECEIVE_NEXT_PAGE = 'RECEIVE_NEXT_PAGE';
export const RECEIVE_NEXT_PAGE_ERROR = 'RECEIVE_NEXT_PAGE_ERROR';
